version: '3.7'
services:
  couch:
    image: couchdb:2.3.1
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-cht}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-cht-password}
    networks:
      - cht-net
  postgres:
    image: postgres:13
    environment:
        POSTGRES_DB: cht
        POSTGRES_USER: cht
        POSTGRES_PASSWORD: cht_password
    networks:
      - cht-net
  sut:
    build:
      context: .
      target: test-couch2pg
      args:
        node_version: '10'
    volumes:
      - ./libs:/usr/app/libs
      - ./tests:/usr/app/tests
    environment:
      TEST_PG_URL: postgres://cht:cht_password@postgres:5432
      TEST_COUCH_URL: http://${COUCHDB_USER:-cht}:${COUCHDB_PASSWORD:-cht-password}@couch:5984

    networks:
      - cht-net
    depends_on:
      - couch
      - postgres

networks:
  cht-net:
    name: cht-net
