name: Build cht-couch2pg and run unit test cases

on: [ push, pull_request ]

jobs:
  build-and-test:
    name: Build cht-couch2pg
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [ 8, 10, 12 ]


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: cht_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      couchdb:
        image: apache/couchdb:2.3.1
        env:
          COUCHDB_USER: cht
          COUCHDB_PASSWORD: cht-password
        ports:
          - 5984:5984

    steps:
      - name: Get Docker Hub username
        id: get-docker-hub-username
        run: echo '::set-output name=dockerhub_username::${{ secrets.CI_DOCKER_USERNAME }}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}
        if: steps.get-docker-hub-username.outputs.dockerhub_username
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build test image and run tests
        run: docker build --build-arg node_version=${{ matrix.node-version }}  --build-arg PG_PASS=cht_password --build-arg COUCH_PASS=cht-password --build-arg COUCH_ADMIN=cht --build-arg PG_SVC=localhost --build-arg COUCHDB_SVC=localhost --target test-couch2pg .

      - name:  Get tags to apply to image
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            medicmobile/cht-couch2pg
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{github.ref == 'refs/heads/arch-v3' || github.event.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
